version: "1.0"
services:
  postgres:
    user: msna
    db: msna
    port: 5432
      #secrets:
      #- POSTGRES_PASSWORD
  pgadmin:
    default_email: admin@example.com
    port: 80
      #secrets:
      #- PGADMIN_DEFAULT_PASSWORD
  jupyterhub:
    port: 8000
  rstudio:
    #user: rstudio
    Base_port: 8787
      #secrets:
      #- RSTUDIO_PASSWORD
  airflow:
    port: 8080
  postgrest:
    port: 3000
    db_schema: public
    db_anon_role: web_anon
  flask:
    port: 5000
  vscode:
    port: 8443
  nginx:
    http_port: 80
    https_port: 443

users: 
  - username: admin
    password: admin
  - username: sunhee
    password: sunhee
  - username: mario
    password: mario
  - username: guillaume
    password: guillaume
